Algoritmo "Exercicio_6"
// Disciplina   : [Linguagem e Lógica de Programação]
// Vanusa
// Data atual  : 17/05/2024
Var

   salario,salario_atual:real


Inicio
   escreva("Digite seu salario: ")
   leia(salario)

   salario_atual<-(salario*1.05)
   escreva("Salario atual com rajuste de 5% será ", salario_atual)



Fimalgoritmo
//Faça um algoritmo que leia
//um valor qualquer e imprima na
//tela com um rajuste de 5%.