Algoritmo "Exercicio_4"
//Vanusa
// Data atual  : 16/05/2024
Var
   numero,antecessor,sucessor:inteiro


Inicio
   escreval("Por favor informe numero ")
   leia(numero)

   antecessor <- numero -1
   sucessor <- numero +1

   escreval("Numero informado ",numero)
   escreval("Antecessor ",antecessor)
   escreval("Sucessor ",sucessor)

Fimalgoritmo

//Faça um algoritmo que receba um número
//inteiro e imprima na tela
//o seu antecessor e o seu sucessor.