Algoritmo "Informa_sexo"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Almir
// Descrição   :
// Autor(a)    : Vanusa
// Data atual  : 03/05/2024
Var
   sexo:inteiro


Inicio
   escreva("Digite sexo (1-Feminino)(2- Masculino: ) " )
   leia(sexo)
   escolha(sexo)

   caso 1
      escreva("sexo Feminino")

   caso 2
      escreva("sexo masculino")

   outrocaso
      escreva("Você digitou errado")
   fimescolha



Fimalgoritmo