Algoritmo "Pode_tirar_carteira_motorista"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Almir
// Descrição   :
// Autor(a)    : Vanusa
// Data atual  : 05/05/2024
Var
   idade:inteiro


Inicio
   escreva(" Digite sua idade ")
   leia(idade)
   se (idade >=18)entao
      escreva( "Pode tirar carteira de motorista")
   senao
      escreva( "Não pode tirar carteira de motorista")
   fimse



Fimalgoritmo