Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 06/05/2024
Var
     contador:inteiro

Inicio
   contador <-1
   enquanto (contador < 10)faça
      escreval(contador)
      contador <-contador +1

   fimEnquanto

Fimalgoritmo