Algoritmo "Separa_numero"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Jonathan
// Descrição   :
// Autor(a)    : vanusa
// Data atual  : 16/05/2024
Var
   numero:real

Inicio
   escreva("Digite numero ")
   leia(numero)
   se (numero =0)entao
      escreva("Numero é nulo")
   senao
      se (numero>0)entao
         escreva("Numero positivo")
      senao
         escreva("Numero negativo")


      fimse
   fimse



Fimalgoritmo