Algoritmo "Verificar_numero"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Almir
// Descrição   :
// Autor(a)    : Vanusa
// Data atual  : 05/05/2024
Var
   //criar algoritimo que diz se x é maior que y
   X,Y:inteiro

Inicio
   escreval(" Digite um valor para X ")
   leia(X)
   Escreval(" Digite um valor para Y ")
   leia(Y)
   se (X > Y)então
      escreva(" X maior que Y")
   senao
      escreva(" X menor que Y ")
   fimse


Fimalgoritmo